CREATE DATABASE AutoAlertDB;
GO

use AutoAlertDB;
GO

CREATE TABLE Groups (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    Name NVARCHAR(150) NOT NULL,
    CreatedAt DATETIME DEFAULT GETDATE(),
    UpdatedAt DATETIME DEFAULT GETDATE()
);
GO

CREATE TABLE Companys (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    Name NVARCHAR(150) NOT NULL,
    IdGroup UNIQUEIDENTIFIER NULL,
    CreatedAt DATETIME DEFAULT GETDATE(),
    UpdatedAt DATETIME DEFAULT GETDATE(),
    FOREIGN KEY (IdGroup) REFERENCES Groups(Id)
);
GO

CREATE TABLE Points (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    Name NVARCHAR(150) NOT NULL,
    Address NVARCHAR(255),
    IdCompany UNIQUEIDENTIFIER NOT NULL,
    CreatedAt DATETIME DEFAULT GETDATE(),
    UpdatedAt DATETIME DEFAULT GETDATE(),
    FOREIGN KEY (IdCompany) REFERENCES Companys(Id)
);
GO

CREATE TABLE Services (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    ServiceType NVARCHAR(100) NOT NULL,
    AccountNumber NVARCHAR(100),
    DueDate DATETIME,
    Amount DECIMAL(12,2),
    Status NVARCHAR(50),
    IdPoint UNIQUEIDENTIFIER NOT NULL,
    CreatedAt DATETIME DEFAULT GETDATE(),
    UpdatedAt DATETIME DEFAULT GETDATE(),
    FOREIGN KEY (IdPoint) REFERENCES Points(Id)
);
GO

CREATE TABLE Alerts (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    IdService UNIQUEIDENTIFIER NOT NULL,
    ScheduledAt DATETIME NOT NULL,
    Channel NVARCHAR(50),
    Status NVARCHAR(50),
    CreatedAt DATETIME DEFAULT GETDATE(),
    UpdatedAt DATETIME DEFAULT GETDATE(),
    FOREIGN KEY (IdService) REFERENCES Services(Id)
);
GO

CREATE TABLE Users (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    Names NVARCHAR(150) NOT NULL,
    LastName NVARCHAR(150),
    Email NVARCHAR(150) UNIQUE NOT NULL,
    Phone NVARCHAR(50),
    Address NVARCHAR(255),
    Password NVARCHAR(255),
    IsActive BIT DEFAULT 1,
    CreatedAt DATETIME DEFAULT GETDATE(),
    UpdatedAt DATETIME DEFAULT GETDATE()
);
GO

CREATE TABLE Notifications (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    IdAlert UNIQUEIDENTIFIER NOT NULL,
    UserId UNIQUEIDENTIFIER NOT NULL,
    SentAt DATETIME,
    Result NVARCHAR(100),
    CreatedAt DATETIME DEFAULT GETDATE(),
    UpdatedAt DATETIME DEFAULT GETDATE(),
    FOREIGN KEY (IdAlert) REFERENCES Alerts(Id),
    FOREIGN KEY (UserId) REFERENCES Users(Id)
);
GO

CREATE TABLE Tickets (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    UserId UNIQUEIDENTIFIER NOT NULL,
    Subject NVARCHAR(150),
    Description NVARCHAR(MAX),
    Status NVARCHAR(50),
    CreatedAt DATETIME DEFAULT GETDATE(),
    UpdatedAt DATETIME DEFAULT GETDATE(),
    FOREIGN KEY (UserId) REFERENCES Users(Id)
);
GO

CREATE TABLE Roles (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    Name NVARCHAR(100) NOT NULL,
    Description NVARCHAR(255),
    CreatedAt DATETIME DEFAULT GETDATE(),
    UpdatedAt DATETIME DEFAULT GETDATE()
);
GO

CREATE TABLE Permissions (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    Code NVARCHAR(100) NOT NULL,
    Name NVARCHAR(150) NOT NULL,
    Module NVARCHAR(100),
    CreatedAt DATETIME DEFAULT GETDATE(),
    UpdatedAt DATETIME DEFAULT GETDATE()
);
GO

CREATE TABLE RolePermissions (
    IdRole UNIQUEIDENTIFIER NOT NULL,
    IdPermission UNIQUEIDENTIFIER NOT NULL,
    IsGranted BIT DEFAULT 1,
    CreatedAt DATETIME DEFAULT GETDATE(),
    UpdatedAt DATETIME DEFAULT GETDATE(),
    PRIMARY KEY (IdRole, IdPermission),
    FOREIGN KEY (IdRole) REFERENCES Roles(Id),
    FOREIGN KEY (IdPermission) REFERENCES Permissions(Id)
);
GO

CREATE TABLE UserRoles (
    IdUser UNIQUEIDENTIFIER NOT NULL,
    IdRole UNIQUEIDENTIFIER NOT NULL,
    CreatedAt DATETIME DEFAULT GETDATE(),
    UpdatedAt DATETIME DEFAULT GETDATE(),
    PRIMARY KEY (IdUser, IdRole),
    FOREIGN KEY (IdUser) REFERENCES Users(Id),
    FOREIGN KEY (IdRole) REFERENCES Roles(Id)
);
GO

CREATE TABLE UserPermissions (
    IdUser UNIQUEIDENTIFIER NOT NULL,
    IdPermission UNIQUEIDENTIFIER NOT NULL,
    IsGranted BIT NULL,
    CreatedAt DATETIME DEFAULT GETDATE(),
    UpdatedAt DATETIME DEFAULT GETDATE(),
    PRIMARY KEY (IdUser, IdPermission),
    FOREIGN KEY (IdUser) REFERENCES Users(Id),
    FOREIGN KEY (IdPermission) REFERENCES Permissions(Id)
);
GO

CREATE TABLE UserCompanys (
    IdUser UNIQUEIDENTIFIER NOT NULL,
    IdCompany UNIQUEIDENTIFIER NOT NULL,
    AccessType NVARCHAR(50) DEFAULT 'view',
    CreatedAt DATETIME DEFAULT GETDATE(),
    UpdatedAt DATETIME DEFAULT GETDATE(),
    PRIMARY KEY (IdUser, IdCompany),
    FOREIGN KEY (IdUser) REFERENCES Users(Id),
    FOREIGN KEY (IdCompany) REFERENCES Companys(Id)
);
GO

CREATE TABLE UserGroups (
    IdUser UNIQUEIDENTIFIER NOT NULL,
    IdGroup UNIQUEIDENTIFIER NOT NULL,
    AccessType NVARCHAR(50) DEFAULT 'view',
    CreatedAt DATETIME DEFAULT GETDATE(),
    UpdatedAt DATETIME DEFAULT GETDATE(),
    PRIMARY KEY (IdUser, IdGroup),
    FOREIGN KEY (IdUser) REFERENCES Users(Id),
    FOREIGN KEY (IdGroup) REFERENCES Groups(Id)
);
